[tool.poetry]
name = "hexlet-code"
version = "0.1.2"
description = ""
authors = ["Konstantin Chupin <chupin.k@yandex.ru>"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "^3.9"
=======
python = "^3.8"
>>>>>>> 8c747a3 (update pyproject.toml)
prompt = "^0.4.1"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain_even:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
